#!/usr/bin/with-contenv bash

# initial crontab files
cp -np /var/www/localhost/initial/crontabs/*	/etc/crontabs/

# initial setting files
cp -npr /var/www/localhost/initial/settings/*	/var/www/localhost/settings/

# initial config file
cp -np /var/www/localhost/initial/config.php	/var/www/localhost/

# daily tasks
if [ ! -L /var/www/localhost/settings/daily_tasks/00_garbageClean.php ]; then
  ln -s /var/www/localhost/bin/garbageClean.php		/var/www/localhost/settings/daily_tasks/00_garbageClean.php
fi
if [ ! -L /var/www/localhost/settings/daily_tasks/10_optimizeTable.php ]; then
  ln -s /var/www/localhost/bin/optimizeTable.php	/var/www/localhost/settings/daily_tasks/10_optimizeTable.php
fi
if [ ! -L /var/www/localhost/settings/daily_tasks/20_radikoStation.php ]; then
  ln -s /var/www/localhost/bin/radikoStation.php	/var/www/localhost/settings/daily_tasks/20_radikoStation.php
fi
